export type Lang = "en" | "zh";

/** Label for the button that switches *to* the other language. */
export const languageSwitch = {
  en: { to: "zh", href: "/zh", label: "中文", aria: "切换到中文" },
  zh: { to: "en", href: "/", label: "EN", aria: "Switch to English" },
} as const;

export const copy = {
  en: {
    htmlLang: "en",
    navAria: "Primary navigation",
    mobileNavAria: "Section navigation",
    skipToContent: "Skip to main content",
    heroIndex: "PORTFOLIO / 2026",
    codeTrackLabel: "TRACK 02",
    nav: ["Profile", "Work", "Approach", "Contact"],
    archiveMenu: "Archive",
    archive: {
      meta: "2026 — ONGOING",
      title: "A growing technical-art archive.",
      body: "One expandable home for the work, notes, and experiments I will keep building over the next year.",
      link: "See the current archive",
      activeLabel: "ACTIVE TRACKS",
      nextLabel: "NEXT TO GROW",
      active: [
        ["Shader Graph / VFX", "4 cases"],
        ["Rendering Code Lab", "4 studies"],
        ["Learning Archive", "3 tracks"],
      ],
      next: [
        ["Tools & Pipeline", "Planned"],
        ["AI × TA Experiments", "Planned"],
        ["Breakdown Notes", "Planned"],
      ],
    },
    available: "Open to internships · campus · full-time roles",
    role: "Technical Artist",
    heroDiscipline: "REAL-TIME GRAPHICS",
    intro:
      "Exploring how AI, art, and code can shape expressive real-time experiences.",
    introNote: "Currently building a foundation in Unity, shaders, C#, and real-time rendering.",
    viewWork: "Explore selected work",
    focusLabel: "Current focus",
    focus: ["Unity", "Shaders", "C# Tooling", "AI × TA"],
    statusLabels: ["Learning", "Practising", "Exploring"],
    sectionLabels: { about: "ABOUT", work: "WORK", process: "PROCESS", contact: "CONTACT" },
    profileEyebrow: "01 / Profile",
    profileTitle: "Building the bridge between visual ideas and real-time systems.",
    profileBody:
      "I’m Smartrick, an emerging Technical Artist building practical knowledge across shader development, Unity tools, and real-time rendering—while exploring where AI can make creative pipelines faster and more expressive.",
    portraitAlt: "Portrait of Smartrick",
    portraitRole: "TECHNICAL ART",
    statusTitle: "Opportunity status",
    statusBody: "Available for internships, campus recruitment, and full-time opportunities.",
    workEyebrow: "02 / Selected practice",
    workTitle: "See the result first. Then explore how it works.",
    workBody:
      "Selected Unity studies presented as clear visual stories: final result, implementation logic, node structure, and code where it exists.",
    highlightsEyebrow: "GET THE HIGHLIGHTS",
    highlightsTitle: "Selected visual systems.",
    highlightsHint: "Choose a case to explore the full breakdown.",
    highlights: [
      { promise: "One timeline. Four visual beats.", metric: "04", metricLabel: "VFX stages", cardTag: "C# Sequence" },
      { promise: "A shield that remembers every hit.", metric: "02", metricLabel: "Ripple slots", cardTag: "Raycast impact" },
      { promise: "Flow, distortion, and glow in one beam.", metric: "10", metricLabel: "Node studies", cardTag: "UV flow" },
      { promise: "A dissolve edge that reads as fire.", metric: "04", metricLabel: "Core modules", cardTag: "Edge emission" },
    ],
    workTrackNavAria: "Work type navigation",
    workTracks: ["Node-based VFX", "Rendering Code Lab"],
    trackNavMeta: ["SHADER GRAPH", "HLSL + C# + URP"],
    trackHeading: "TRACK 01 / NODE-BASED VFX",
    visualTrack: "Shader Graph / Visual VFX",
    visualTrackBody: "Four complete visual case studies, organized by their original Unity folders.",
    codeEyebrow: "Handwritten Shaders / URP Pipeline",
    codeTitle: "Rendering Code Lab",
    codeBody:
      "Selected studies from my public Unity-Shader learning archive. These cases show how I connect ShaderLab and HLSL with C#, Renderer Features, RenderGraph, and runtime rendering systems.",
    codeLearningNote: "Learning archive · implementations and adaptations",
    flowLabel: "Implementation flow",
    snippetLabel: "Core logic",
    viewCode: "View code",
    viewRepo: "View full GitHub repository",
    archiveEyebrow: "Full learning archive",
    archiveTitle: "Beyond the four featured cases.",
    archiveBody:
      "The repository also records the wider learning path from lighting fundamentals to URP custom rendering. Expand a track to browse every chapter.",
    openChapter: "Open chapter",
    lab: {
      header: "PROJECT LAB / ACTIVE SYSTEM",
      selectAria: "Select project",
      toolsAria: "Project lab tools",
      views: { result: "Result", gallery: "Gallery", logic: "Logic", nodes: "Nodes", code: "Code" },
      expand: "Expand",
      unavailable: "This media is currently unavailable.",
      unavailableSource: "This source file is currently unavailable.",
      inspectorAria: "Project inspector",
      readNotes: "Read technical notes",
      implLogic: "Implementation logic",
      openSource: "Open source file",
      scriptNote: "This code controls the active project’s runtime behavior.",
      closeViewer: "Close fullscreen viewer",
      showVideoPrefix: "Show result video",
      resultVideosAria: "Result videos",
      expandNode: "Expand node graph",
      expandCode: "Expand code",
      playVideo: "Play project video",
    },
    projects: [
      {
        title: "Full Skill Effect",
        description:
          "A complete sci-fi skill sequence driven by C#, coordinating charge-up, beam fade-in, impact pulse, explosion radius, dissolve, and emission timing.",
        tags: ["Unity 6", "Shader Graph", "C# Sequence"],
        logic: [
          "Split the skill into charge, beam, hit, and explosion materials so every stage can be tuned independently.",
          "Use a C# timeline to trigger each phase and write radius, dissolve, emission, and opacity values into the materials.",
          "Keep the visual hand-off continuous: the charge releases into the beam, the hit pulse marks contact, and the explosion resolves the sequence.",
        ],
      },
      {
        title: "Interactive Energy Shield",
        description:
          "An energy shield combining Fresnel edges, layered patterns, core veins, noise distortion, and two alternating impact slots controlled by raycast input.",
        tags: ["Shader Graph", "C#", "Raycast"],
        logic: [
          "Construct the shield surface from a Fresnel shell, panel pattern, core veins, and controlled distortion.",
          "Raycast from the pointer into the shield and pass the local hit position plus start time to the material.",
          "Alternate between two impact slots so a second ripple can begin before the previous one has fully faded.",
        ],
      },
      {
        title: "Energy Beam",
        description:
          "A real-time beam effect built from animated UV flow, distortion, core and glow layers, start/end clipping, and hit-point highlighting.",
        tags: ["Shader Graph", "UV Flow", "VFX"],
        logic: [
          "Scroll and distort the beam UVs to create directional energy instead of a static texture.",
          "Separate the concentrated core from the wider glow so brightness and softness can be authored independently.",
          "Clip the beam at both ends, then add start and hit highlights to visually anchor it in the scene.",
        ],
      },
      {
        title: "Stylized Dissolve Fire",
        description:
          "A stylized fire and dissolve study using UV-based masks, animated breakup, layered base color, and emissive edge treatment.",
        tags: ["Dissolve", "Emission", "Material"],
        logic: [
          "Build a stable UV-space mask, then introduce animated breakup so the dissolve edge feels organic.",
          "Use the dissolve threshold to separate visible surface, transition band, and removed pixels.",
          "Layer base color with a narrow emissive edge so the material reads as burning rather than simply disappearing.",
        ],
      },
    ],
    approachEyebrow: "03 / Approach",
    approachTitle: "Art sets the intent. Code makes it real. AI expands the search space.",
    approachBody:
      "I’m early in the journey, so the portfolio focuses on process: what I tried, what broke, what I learned, and how I would improve the result.",
    pillars: [
      ["ART", "Observe form, color, motion, and visual hierarchy."],
      ["CODE", "Turn an idea into a repeatable real-time system."],
      ["AI", "Use new tools to explore faster—without hiding the craft."],
    ],
    contactEyebrow: "04 / Contact",
    contactTitle: "Let’s build the next frame.",
    contactBody: "Open to opportunities in Technical Art and real-time graphics.",
    contactCards: [
      ["DIRECT CONTACT", "Email", "ke4773613@gmail.com"],
      ["TECHNICAL PROFILE", "GitHub", "@smartrick125"],
      ["PERSONAL LIFE ACCOUNT", "Douyin", "@ww2024260424"],
      ["CAREER DOCUMENT", "Résumé", "Coming soon"],
    ],
    footer: "Designed as a portfolio in progress",
    stage: "Phase 02 — Case studies",
    backToTop: "TOP",
  },

  zh: {
    htmlLang: "zh-CN",
    navAria: "主导航",
    mobileNavAria: "分区导航",
    skipToContent: "跳到主要内容",
    heroIndex: "作品集 / 2026",
    codeTrackLabel: "方向 02",
    nav: ["简介", "作品", "方法", "联系"],
    archiveMenu: "归档",
    archive: {
      meta: "2026 — 持续更新",
      title: "一个还在长的技术美术归档。",
      body: "接下来一年要做的东西、笔记和实验，都会往这里放。",
      link: "查看当前归档",
      activeLabel: "进行中的方向",
      nextLabel: "接下来会补充",
      active: [
        ["Shader Graph / 视觉特效", "4 个案例"],
        ["渲染代码实验室", "4 个研究"],
        ["学习归档", "3 条主线"],
      ],
      next: [
        ["工具与管线", "计划中"],
        ["AI × TA 实验", "计划中"],
        ["拆解笔记", "计划中"],
      ],
    },
    available: "接受实习 · 校招 · 社招机会",
    role: "技术美术 / TA",
    heroDiscipline: "实时图形",
    intro: "想弄清楚 AI、艺术和代码放在一起，能把实时画面推到什么程度。",
    introNote: "正在打 Unity、Shader、C# 和实时渲染的底子。",
    viewWork: "查看实践项目",
    focusLabel: "当前方向",
    focus: ["Unity", "Shader", "C# 工具", "AI × TA"],
    statusLabels: ["学习中", "实践中", "探索中"],
    sectionLabels: { about: "关于", work: "作品", process: "方法", contact: "联系" },
    profileEyebrow: "01 / 个人简介",
    profileTitle: "在画面表达和实时系统之间搭一座桥。",
    profileBody:
      "我是 Smartrick，正在往技术美术方向走。现在主要在补 Shader 开发、Unity 工具和实时渲染这几块，同时也在试 AI 能把创作流程推到哪一步。",
    portraitAlt: "Smartrick 的个人照片",
    portraitRole: "技术美术",
    statusTitle: "求职状态",
    statusBody: "实习、校招、社招都可以聊。",
    workEyebrow: "02 / 实践项目",
    workTitle: "先看效果，再看它是怎么做出来的。",
    workBody:
      "挑出来的几个 Unity 练习，都按同一条线讲：先看成品，再看实现逻辑和节点结构，有源码的一并放上。",
    highlightsEyebrow: "先看这几个",
    highlightsTitle: "挑出来的几套视觉。",
    highlightsHint: "点开任意一个，看完整拆解。",
    highlights: [
      { promise: "一条时间线，四段视觉节拍。", metric: "04", metricLabel: "特效阶段", cardTag: "C# 时序" },
      { promise: "记得住每一次击中的护盾。", metric: "02", metricLabel: "涟漪通道", cardTag: "射线冲击" },
      { promise: "流动、扭曲和辉光，汇进同一束光。", metric: "10", metricLabel: "节点研究", cardTag: "UV 流动" },
      { promise: "溶解的边缘，看着像在烧。", metric: "04", metricLabel: "核心模块", cardTag: "边缘自发光" },
    ],
    workTrackNavAria: "作品类型导航",
    workTracks: ["节点式视觉特效", "渲染代码实验室"],
    trackNavMeta: ["SHADER GRAPH", "HLSL + C# + URP"],
    trackHeading: "方向 01 / 节点式视觉特效",
    visualTrack: "Shader Graph / 视觉特效",
    visualTrackBody: "四个完整案例，按原来的 Unity 文件夹分类放着。",
    codeEyebrow: "手写 Shader / URP 渲染管线",
    codeTitle: "渲染代码实验室",
    codeBody:
      "从公开的 Unity-Shader 学习仓库里挑出来的几个案例，主要想说清楚我是怎么把 ShaderLab、HLSL 和 C#、Renderer Feature、RenderGraph 串到一起的。",
    codeLearningNote: "学习归档 · 跟着实现和改写",
    flowLabel: "实现流程",
    snippetLabel: "核心逻辑",
    viewCode: "查看源码",
    viewRepo: "查看完整 GitHub 仓库",
    archiveEyebrow: "完整学习归档",
    archiveTitle: "精选之外，还有这些。",
    archiveBody:
      "仓库里留着从基础光照一路到 URP 自定义渲染的完整过程，展开就能翻到每一章。",
    openChapter: "打开章节",
    lab: {
      header: "项目实验台 / 当前系统",
      selectAria: "选择项目",
      toolsAria: "项目实验台工具",
      views: { result: "效果", gallery: "图集", logic: "逻辑", nodes: "节点", code: "源码" },
      expand: "放大",
      unavailable: "该素材暂时无法显示。",
      unavailableSource: "该源文件暂时无法显示。",
      inspectorAria: "项目详情",
      readNotes: "展开技术总结",
      implLogic: "实现逻辑",
      openSource: "打开源文件",
      scriptNote: "这段代码控制当前项目在运行时的表现。",
      closeViewer: "关闭全屏查看",
      showVideoPrefix: "播放效果录屏",
      resultVideosAria: "效果录屏",
      expandNode: "放大节点图",
      expandCode: "放大代码",
      playVideo: "播放项目视频",
    },
    projects: [
      {
        title: "完整技能特效",
        description:
          "通过 C# 统一编排科幻技能序列，控制蓄力、光束渐入、命中脉冲、爆炸半径、溶解与自发光时间。",
        tags: ["Unity 6", "Shader Graph", "C# 时序"],
        logic: [
          "把技能拆分为蓄力、光束、命中和爆炸四套材质，让每个阶段都能独立调节。",
          "使用 C# 时间序列触发各阶段，并持续写入半径、溶解、自发光和透明度参数。",
          "保证视觉衔接连续：蓄力释放为光束，命中脉冲标记接触点，最后由爆炸完成收束。",
        ],
      },
      {
        title: "交互式能量护盾",
        description:
          "结合 Fresnel、分层图案、核心脉络与噪声扭曲，并通过射线点击交替驱动两组护盾冲击涟漪。",
        tags: ["Shader Graph", "C#", "Raycast"],
        logic: [
          "使用 Fresnel 外壳、面板图案、核心脉络和噪声扭曲共同构建护盾表面。",
          "从指针位置向护盾发射射线，把局部命中坐标与开始时间传入材质。",
          "交替使用两组冲击槽，让第二次涟漪可以在上一轮完全消失前继续触发。",
        ],
      },
      {
        title: "能量光束",
        description:
          "使用 UV 流动、噪声扭曲、核心辉光、起止位置裁切和命中点高亮构建实时光束效果。",
        tags: ["Shader Graph", "UV 流动", "VFX"],
        logic: [
          "让光束 UV 定向滚动并叠加扭曲，避免能量纹理看起来静止。",
          "把高亮核心与外层辉光分开计算，使亮度和柔和范围可以独立控制。",
          "在两端裁切光束，并添加起点与命中点高亮，让它在场景中具有明确连接关系。",
        ],
      },
      {
        title: "风格化溶解火焰",
        description:
          "基于 UV 遮罩、动态破碎、分层基础色与边缘自发光制作风格化火焰溶解效果。",
        tags: ["溶解", "自发光", "材质"],
        logic: [
          "先建立稳定的 UV 空间遮罩，再加入动态破碎，让溶解边缘更自然。",
          "使用溶解阈值划分保留表面、过渡边缘和被裁切区域。",
          "将基础色与窄范围自发光边缘叠加，使材质更像燃烧，而不是简单消失。",
        ],
      },
    ],
    approachEyebrow: "03 / 方法",
    approachTitle: "艺术定方向，代码让它跑起来，AI 把路子拓宽。",
    approachBody:
      "我还在补基础，所以这个作品集更想讲过程：试了什么、哪里卡住了、学到了什么、下次会怎么改。",
    pillars: [
      ["ART", "看形状、看颜色、看动势、看层次。"],
      ["CODE", "把一个想法做成能反复跑的实时系统。"],
      ["AI", "用新工具跑得更快，但基本功不拿它替。"],
    ],
    contactEyebrow: "04 / 联系",
    contactTitle: "一起做出下一帧。",
    contactBody: "技术美术和实时图形方向的机会，都欢迎来聊。",
    contactCards: [
      ["直接联系", "邮箱", "ke4773613@gmail.com"],
      ["技术主页", "GitHub", "@smartrick125"],
      ["个人生活账号", "抖音", "@ww2024260424"],
      ["求职材料", "简历", "待补充"],
    ],
    footer: "一个还在长的作品集",
    stage: "阶段 02 — 项目案例",
    backToTop: "顶部",
  },
} as const;

export type Dict = (typeof copy)["en"];
